version: 2
updates:
- package-ecosystem: gradle
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: com.github.kt3k.coveralls
    versions:
    - 2.10.2
    - 2.11.0
  - dependency-name: org.mockito:mockito-core
    versions:
    - 3.7.7
    - 3.8.0
  - dependency-name: com.badlogicgames.gdx:gdx-backend-headless
    versions:
    - 1.9.13
    - 1.9.14
  - dependency-name: com.badlogicgames.gdx:gdx
    versions:
    - 1.9.13
    - 1.9.14
  - dependency-name: com.badlogicgames.gdx:gdx-box2d
    versions:
    - 1.9.13
    - 1.9.14
  - dependency-name: com.badlogicgames.gdx:gdx-freetype
    versions:
    - 1.9.13
    - 1.9.14
  - dependency-name: com.badlogicgames.gdx:gdx-backend-android
    versions:
    - 1.9.13
    - 1.9.14
  - dependency-name: com.android.tools.build:gradle
    versions:
    - 4.1.2
  - dependency-name: com.google.guava:guava
    versions:
    - 30.1-android
  - dependency-name: junit:junit
    versions:
    - 4.13.1
